### ISSUE TITLE
Simplify CSS for shared properties.

### ISSUE THREAD

**Issue by josephtkim** [bhassan6621/prj-rev-bwfs-dasmoto#7]
It is a good idea to try and simplify the CSS code as much as you can to make the code cleaner and to remove repetitive code. There are a few shared properties that you can simplify by applying to multiple selectors at once, rather than individually. For instance, 

```css
#header, h2, .startingAt {
  font-family: Helvetica;
  font-weight: bold;
}
```
